services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: .             # プロジェクトルートをビルドコンテキストに設定
      dockerfile: Dockerfile  # ルートにある Dockerfile を使用
    container_name: hono_app
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/app       # backend ディレクトリを /app にマウント
    depends_on:
      - db
    command: npm run dev

volumes:
  mysql_data: